name: Merge release fixes into main after production release

on:
  pull_request:
    types: [closed]
    branches:
      - production

permissions:
  contents: write
  pull-requests: write

jobs:
  sync-release-to-main:
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'release/')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Sync release branch into main
        env:
          GITHUB_TOKEN: ${{ secrets.MY_PAT }}
        run: |
          RELEASE_BRANCH="${{ github.event.pull_request.head.ref }}"
          TEMP_BRANCH="backmerge-production-to-main-${{ github.run_id }}"

          git checkout -b $TEMP_BRANCH origin/production
          git push origin $TEMP_BRANCH

          gh pr create \
            --title "Backmerge prod to main after $RELEASE_BRANCH" \
            --body "This PR merges the latest changes from \`production\` into \`main\` after a production release." \
            --base main \
            --head $TEMP_BRANCH
