name: Merge release fixes into main after production release

on:
  pull_request:
    types: [closed]
    branches:
      - production

permissions:
  contents: write
  pull-requests: write

jobs:
  sync-release-to-main:
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'release/')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Sync release branch into main
        env:
          GITHUB_TOKEN: ${{ secrets.MY_PAT }}
        run: |
          RELEASE_BRANCH="${{ github.event.pull_request.head.ref }}"
          TEMP_BRANCH="merge-${RELEASE_BRANCH//\//-}-to-main"

          git checkout main
          git pull origin main

          git checkout -b $TEMP_BRANCH
          git merge origin/$RELEASE_BRANCH --no-ff -m "Merge $RELEASE_BRANCH into main"

          git push origin $TEMP_BRANCH

          gh pr create \
            --title "Merge $RELEASE_BRANCH into main" \
            --body "Merging release fixes from \`$RELEASE_BRANCH\` into \`main\` after production release." \
            --base main \
            --head $TEMP_BRANCH
