name: Open PR to main when PR is merged into release branch

on:
  pull_request:
    types: [closed]

jobs:
  create-pr:
    if: |
      github.event.pull_request.merged == true &&
      startsWith(github.event.pull_request.base.ref, 'release/')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Extract source branch name
        id: extract
        run: |
          SOURCE_BRANCH="${{ github.event.pull_request.head.ref }}"
          echo "source_branch=$SOURCE_BRANCH" >> $GITHUB_OUTPUT

      - name: Create PR to main from source branch
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.MY_PAT }}
          source_branch: ${{ steps.extract.outputs.source_branch }}
          destination_branch: main
          pr_title: '🔀 Merge `${{ steps.extract.outputs.source_branch }}` into main'
          pr_body: |
            This PR was automatically created because `${{ steps.extract.outputs.source_branch }}` was merged into a release branch.
          github_token: ${{ secrets.GITHUB_TOKEN }}
