name: Open PR to main when merged into release

on:
  pull_request:
    types: [closed]
    branches:
      - release/**

permissions:
  contents: write
  pull-requests: write

jobs:
  open-pr-to-main:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create PR to main
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.MY_PAT }}
          script: |
            const sourceBranch = context.payload.pull_request.head.ref;
            const originalTitle = context.payload.pull_request.title;
            const newTitle = `${originalTitle} on the main`;

            const response = await github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: newTitle,
              head: sourceBranch,
              base: "main",
              body: `Automated PR from \`${sourceBranch}\` to \`main\``
            });

            console.log("✅ PR created:", response.data.html_url);
