name: Merge release into main when fix is merged

on:
  pull_request:
    types: [closed]
    branches:
      - release/**

permissions:
  contents: write
  pull-requests: write

jobs:
  merge-release-to-main:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Merge release into main and create PR
        env:
          GITHUB_TOKEN: ${{ secrets.MY_PAT }}
        run: |
          RELEASE_BRANCH="${GITHUB_REF#refs/heads/}"
          MAIN_BRANCH="main"
          TEMP_BRANCH="merge-${RELEASE_BRANCH}-to-main"

          git checkout $MAIN_BRANCH
          git pull origin $MAIN_BRANCH

          git checkout -b $TEMP_BRANCH
          git merge origin/$RELEASE_BRANCH --no-ff -m "Merge $RELEASE_BRANCH into main"

          git push origin $TEMP_BRANCH

          gh pr create \
            --title "Merge $RELEASE_BRANCH into main" \
            --body "Auto-merge of release branch \`$RELEASE_BRANCH\` into \`main\` after fix merged." \
            --base "$MAIN_BRANCH" \
            --head "$TEMP_BRANCH"
